site_name: Landing Zone Accelerator on AWS
site_url: !ENV [SITE_URL, https://awslabs.github.io/landing-zone-accelerator-on-aws/]
site_author: Amazon Web Services
site_description: Documentation for the Landing Zone Accelerator on AWS
repo_url: https://github.com/awslabs/landing-zone-accelerator-on-aws/

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
    - user-guide/index.md
    - Services, Features, and Configuration References: user-guide/config.md
    - Centralized Logging: user-guide/logging.md
  - Developer Guide:
    - developer-guide/index.md
    - Development Dependencies: developer-guide/dependencies.md
    - Command Line Interface and Package Scripts: developer-guide/scripts.md
    - Architecture and Design Philosophy: developer-guide/design.md
    - Feature Development: developer-guide/features.md
  - Sample Configurations:
    - sample-configurations/index.md
    - Standard:
      - sample-configurations/standard/index.md
      - Overview: sample-configurations/standard/overview.md
      - Organization and Account Structure: sample-configurations/standard/org-structure.md
      - Authentication and Authorization: sample-configurations/standard/authn-authz.md
      - Logging and Monitoring: sample-configurations/standard/logging-monitoring.md
      - Networking: sample-configurations/standard/networking.md
    - GovCloud (US):
      - sample-configurations/govcloud-us/index.md
      - Overview: sample-configurations/govcloud-us/overview.md
      - Organization and Account Structure: sample-configurations/govcloud-us/org-structure.md
      - Security Controls: sample-configurations/govcloud-us/security-controls.md
      - Networking: sample-configurations/govcloud-us/networking.md
      - Additional Considerations: sample-configurations/govcloud-us/considerations.md
  - FAQ: 
      - faq/index.md
      - General: faq/general.md
      - Architecture: faq/architecture.md
      - AWS Control Tower and Customizations for Control Tower: faq/ct-cfct.md
      - Operations: faq/operations.md
      - Networking:
        - General: faq/networking/general.md
        - Deep Packet Inspection: faq/networking/dpi.md
        - AWS Direct Connect: faq/networking/direct-connect.md
        - AWS Network Firewall: faq/networking/network-firewall.md
        - AWS Gateway Load Balancer: faq/networking/gwlb.md
      - Security: faq/security.md
  - TypeDocs:
    - typedocs/index.md
    - v1.0:
      - v1.0.0: typedocs/v1.0.0/index.html
      - v1.0.1: typedocs/v1.0.1/index.html
    - v1.1:
      - v1.1.0: typedocs/v1.1.0/index.html
    - v1.2: 
      - v1.2.0: typedocs/v1.2.0/index.html
      - v1.2.1: typedocs/v1.2.1/index.html
      - v1.2.2: typedocs/v1.2.2/index.html
    - v1.3: 
      - v1.3.0: typedocs/v1.3.0/index.html
      - v1.3.1: typedocs/v1.3.1/index.html
      - v1.3.2: typedocs/v1.3.2/index.html
    - v1.4: 
      - v1.4.0: typedocs/v1.4.0/index.html
      - v1.4.1: typedocs/v1.4.1/index.html
      - v1.4.2: typedocs/v1.4.2/index.html
      - v1.4.3: typedocs/v1.4.3/index.html
    - v1.5:
      - v1.5.0: typedocs/v1.5.0/index.html
      - v1.5.1: typedocs/v1.5.1/index.html
      - v1.5.2: typedocs/v1.5.2/index.html
    - v1.6:
      - v1.6.0: typedocs/v1.6.0/index.html
      - v1.6.1: typedocs/v1.6.1/index.html
      

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - typescript
  features:
    - content.code.copy
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - navigation.top
  icon:
    logo: material/rocket-launch
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: ⚓︎