homeRegion: &HOME_REGION us-east-1
defaultVpc:
  delete: true
  excludeAccounts: []
transitGateways:
  - name: Network-Main
    account: Network-Prod
    region: *HOME_REGION
    shareTargets:
      organizationalUnits:
        - Infrastructure
        - HIS
        - EIS
    asn: 65521
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: disable
    autoAcceptSharingAttachments: enable
    routeTables:
      - name: Network-Main-Core
        routes: []
      - name: Network-Main-Spoke
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            attachment:
              vpcName: Network-Inspection
              account: Network-Prod
centralNetworkServices:
  delegatedAdminAccount: Network-Prod
  networkFirewall:
    firewalls:
      - name: accelerator-firewall
        region: *HOME_REGION
        firewallPolicy: accelerator-policy
        subnets:
          - Network-Inspection-A
          - Network-Inspection-B
        vpc: Network-Inspection
        loggingConfiguration:
          - destination: s3
            type: ALERT
          - destination: cloud-watch-logs
            type: FLOW
    policies:
      - name: accelerator-policy
        regions:
          - *HOME_REGION
        firewallPolicy:
          statelessDefaultActions: ["aws:forward_to_sfe"]
          statelessFragmentDefaultActions: ["aws:forward_to_sfe"]
          statefulRuleGroups:
            - name: accelerator-rule-group
            - name: domain-list-group
        shareTargets:
          organizationalUnits:
            - Infrastructure
    rules:
      - name: accelerator-rule-group
        regions:
          - *HOME_REGION
        capacity: 100
        type: STATEFUL
        ruleGroup:
          rulesSource:
            statefulRules:
              # Block traffic between production VPCs
              - action: DROP
                header:
                  destination: 10.3.0.0/16
                  destinationPort: ANY
                  direction: ANY
                  protocol: IP
                  source: 10.4.0.0/16
                  sourcePort: ANY
                ruleOptions:
                  - keyword: sid
                    settings: ["100"]
      - name: domain-list-group
        regions:
          - *HOME_REGION
        capacity: 10
        type: STATEFUL
        ruleGroup:
          rulesSource:
            rulesSourceList:
              generatedRulesType: DENYLIST
              # Add/Modify the domain list per business needs.
              targets: [".google.com"]
              targetTypes: ["TLS_SNI", "HTTP_HOST"]
          ruleVariables:
            ipSets:
              name: HOME_NET
              definition:
                - 10.1.0.0/16
                - 10.2.0.0/16
                - 10.3.0.0/16
                - 10.4.0.0/16
            portSets:
              name: HOME_NET
              definition:
                - "80"
                - "443"
  route53Resolver:
    endpoints: []
    queryLogs:
      name: accelerator-query-logs
      destinations:
        - s3
        - cloud-watch-logs
      shareTargets:
        organizationalUnits:
          - Infrastructure
    firewallRuleGroups:
      - name: accelerator-block-group
        regions:
          - *HOME_REGION
        rules:
          - name: managed-rule
            action: BLOCK
            managedDomainList: AWSManagedDomainsBotnetCommandandControl
            priority: 300
            blockResponse: NODATA
        shareTargets:
          organizationalUnits:
            - Infrastructure
endpointPolicies:
  - name: Default
    document: vpc-endpoint-policies/default.json
  - name: Ec2
    document: vpc-endpoint-policies/ec2.json
vpcs:
  - name: Network-Endpoints
    account: Network-Prod
    region: *HOME_REGION
    cidrs:
      - 10.1.0.0/22
    internetGateway: false
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    queryLogs:
      - accelerator-query-logs
    routeTables:
      - name: Network-Endpoints-Tgw-A
        routes: []
      - name: Network-Endpoints-Tgw-B
        routes: []
      - name: Network-Endpoints-A
        routes:
          - name: TgwRoute
            destination: 0.0.0.0/0
            type: transitGateway
            target: Network-Main
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
      - name: Network-Endpoints-B
        routes:
          - name: TgwRoute
            destination: 0.0.0.0/0
            type: transitGateway
            target: Network-Main
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
    subnets:
      - name: Network-Endpoints-A
        availabilityZone: a
        routeTable: Network-Endpoints-A
        ipv4CidrBlock: 10.1.0.0/24
      - name: Network-Endpoints-B
        availabilityZone: b
        routeTable: Network-Endpoints-B
        ipv4CidrBlock: 10.1.1.0/24
      - name: Network-EndpointsTgwAttach-A
        availabilityZone: a
        routeTable: Network-Endpoints-Tgw-A
        ipv4CidrBlock: 10.1.3.208/28
      - name: Network-EndpointsTgwAttach-B
        availabilityZone: b
        routeTable: Network-Endpoints-Tgw-B
        ipv4CidrBlock: 10.1.3.224/28
    transitGatewayAttachments:
      - name: Network-Endpoints
        transitGateway:
          name: Network-Main
          account: Network-Prod
        routeTableAssociations:
          - Network-Main-Core
        routeTablePropagations:
          - Network-Main-Spoke
          - Network-Main-Core
        subnets:
          - Network-EndpointsTgwAttach-A
          - Network-EndpointsTgwAttach-B
    gatewayEndpoints:
      defaultPolicy: Default
      endpoints:
        - service: s3
        - service: dynamodb
    interfaceEndpoints:
      central: true
      defaultPolicy: Default
      subnets:
        - Network-Endpoints-A
        - Network-Endpoints-B
      endpoints:
        - service: ec2
        - service: ec2messages
        - service: ssm
        - service: ssmmessages
        - service: kms
        - service: logs
  - name: Network-Inspection
    account: Network-Prod
    region: *HOME_REGION
    cidrs:
      - 10.2.0.0/22
    internetGateway: true
    routeTables:
      - name: Network-Inspection-Tgw-A
        routes:
          - name: NfwRoute
            destination: 0.0.0.0/0
            type: networkFirewall
            target: accelerator-firewall
            targetAvailabilityZone: a
      - name: Network-Inspection-Tgw-B
        routes:
          - name: NfwRoute
            destination: 0.0.0.0/0
            type: networkFirewall
            target: accelerator-firewall
            targetAvailabilityZone: b
      - name: Network-Inspection-A
        routes:
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: Nat-Network-Inspection-A
          - name: TgwRoute
            destination: 10.0.0.0/8
            type: transitGateway
            target: Network-Main
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
      - name: Network-Inspection-B
        routes:
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: Nat-Network-Inspection-B
          - name: TgwRoute
            destination: 10.0.0.0/8
            type: transitGateway
            target: Network-Main
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
      - name: Network-Inspection-Nat-A
        routes:
          - name: NfwNatRoute
            destination: 10.0.0.0/8
            type: networkFirewall
            target: accelerator-firewall
            targetAvailabilityZone: a
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
      - name: Network-Inspection-Nat-B
        routes:
          - name: NfwNatRoute
            destination: 10.0.0.0/8
            type: networkFirewall
            target: accelerator-firewall
            targetAvailabilityZone: b
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
    subnets:
      - name: Network-Inspection-A
        availabilityZone: a
        routeTable: Network-Inspection-A
        ipv4CidrBlock: 10.2.0.0/24
      - name: Network-Inspection-B
        availabilityZone: b
        routeTable: Network-Inspection-B
        ipv4CidrBlock: 10.2.1.0/24
      - name: Network-InspectionTgwAttach-A
        availabilityZone: a
        routeTable: Network-Inspection-Tgw-A
        ipv4CidrBlock: 10.2.3.208/28
      - name: Network-InspectionTgwAttach-B
        availabilityZone: b
        routeTable: Network-Inspection-Tgw-B
        ipv4CidrBlock: 10.2.3.224/28
      - name: Network-InspectionNat-A
        availabilityZone: a
        routeTable: Network-Inspection-Nat-A
        ipv4CidrBlock: 10.2.3.176/28
      - name: Network-InspectionNat-B
        availabilityZone: b
        routeTable: Network-Inspection-Nat-B
        ipv4CidrBlock: 10.2.3.192/28
    natGateways:
      - name: Nat-Network-Inspection-A
        subnet: Network-InspectionNat-A
      - name: Nat-Network-Inspection-B
        subnet: Network-InspectionNat-B
    transitGatewayAttachments:
      - name: Network-Inspection
        transitGateway:
          name: Network-Main
          account: Network-Prod
        options:
          applianceModeSupport: enable
        routeTableAssociations:
          - Network-Main-Core
        routeTablePropagations: []
        subnets:
          - Network-InspectionTgwAttach-A
          - Network-InspectionTgwAttach-B
    gatewayEndpoints:
      defaultPolicy: Default
      endpoints:
        - service: s3
        - service: dynamodb
    useCentralEndpoints: true
  - name: HIS-pacs-Non-Prod-Main
    account: Pacs-Non_prod
    region: *HOME_REGION
    cidrs:
      - 10.4.0.0/16
    routeTables:
      - name: HIS-pacs-Non-Prod-Tgw-A
        routes: []
      - name: HIS-pacs-Non-Prod-Tgw-B
        routes: []
      - name: HIS-pacs-Non-Prod-App-A
        routes:
          - name: TgwRoute
            destination: 0.0.0.0/0
            type: transitGateway
            target: Network-Main
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
      - name: HIS-pacs-Non-Prod-App-B
        routes:
          - name: TgwRoute
            destination: 0.0.0.0/0
            type: transitGateway
            target: Network-Main
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
    subnets:
      - name: HIS-pacs-Non-Prod-App-A
        availabilityZone: a
        routeTable: HIS-pacs-Non-Prod-App-A
        ipv4CidrBlock: 10.4.0.0/24
      - name: HIS-pacs-Non-Prod-App-B
        availabilityZone: b
        routeTable: HIS-pacs-Non-Prod-App-B
        ipv4CidrBlock: 10.4.1.0/24
      - name: HIS-pacs-Non-Prod-MainTgwAttach-A
        availabilityZone: a
        routeTable: HIS-pacs-Non-Prod-Tgw-A
        ipv4CidrBlock: 10.4.255.208/28
      - name: HIS-pacs-Non-Prod-MainTgwAttach-B
        availabilityZone: b
        routeTable: HIS-pacs-Non-Prod-Tgw-B
        ipv4CidrBlock: 10.4.255.224/28
    transitGatewayAttachments:
      - name: HIS-pacs-Non-Prod-Main
        transitGateway:
          name: Network-Main
          account: Network-Prod
        routeTableAssociations:
          - Network-Main-Spoke
        routeTablePropagations:
          - Network-Main-Core
        subnets:
          - HIS-pacs-Non-Prod-MainTgwAttach-A
          - HIS-pacs-Non-Prod-MainTgwAttach-B
    gatewayEndpoints:
      defaultPolicy: Default
      endpoints:
        - service: s3
        - service: dynamodb
    useCentralEndpoints: true
  - name: HIS-pms-Prod-Main
    account: Pms-Prod
    region: *HOME_REGION
    cidrs:
      - 10.3.0.0/16
    routeTables:
      - name: HIS-pms-Prod-Tgw-A
        routes: []
      - name: HIS-pms-Prod-Tgw-B
        routes: []
      - name: HIS-pms-Prod-App-A
        routes:
          - name: TgwRoute
            destination: 0.0.0.0/0
            type: transitGateway
            target: Network-Main
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
      - name: HIS-pms-Prod-App-B
        routes:
          - name: TgwRoute
            destination: 0.0.0.0/0
            type: transitGateway
            target: Network-Main
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
    subnets:
      - name: HIS-pms-Prod-App-A
        availabilityZone: a
        routeTable: HIS-pms-Prod-App-A
        ipv4CidrBlock: 10.3.0.0/24
      - name: HIS-pms-Prod-App-B
        availabilityZone: b
        routeTable: HIS-pms-Prod-App-B
        ipv4CidrBlock: 10.3.1.0/24
      - name: HIS-pms-Prod-MainTgwAttach-A
        availabilityZone: a
        routeTable: HIS-pms-Prod-Tgw-A
        ipv4CidrBlock: 10.3.255.208/28
      - name: HIS-pms-Prod-MainTgwAttach-B
        availabilityZone: b
        routeTable: HIS-pms-Prod-Tgw-B
        ipv4CidrBlock: 10.3.255.224/28
    transitGatewayAttachments:
      - name: HIS-pms-Prod-Main
        transitGateway:
          name: Network-Main
          account: Network-Prod
        routeTableAssociations:
          - Network-Main-Spoke
        routeTablePropagations:
          - Network-Main-Core
        subnets:
          - HIS-pms-Prod-MainTgwAttach-A
          - HIS-pms-Prod-MainTgwAttach-B
    gatewayEndpoints:
      defaultPolicy: Default
      endpoints: []
    useCentralEndpoints: true
vpcFlowLogs:
  trafficType: ALL
  maxAggregationInterval: 600
  destinations:
    - cloud-watch-logs
  destinationsConfig:
    cloudWatchLogs:
      retentionInDays: 30
  defaultFormat: false
  customFields:
    - version
    - account-id
    - interface-id
    - srcaddr
    - dstaddr
    - srcport
    - dstport
    - protocol
    - packets
    - bytes
    - start
    - end
    - action
    - log-status
    - vpc-id
    - subnet-id
    - instance-id
    - tcp-flags
    - type
    - pkt-srcaddr
    - pkt-dstaddr
    - region
    - az-id
    - pkt-src-aws-service
    - pkt-dst-aws-service
    - flow-direction
    - traffic-path
