# If using AWS Control Tower, ensure that all the specified Organizational Units (OU)
# have been created and enrolled as the accelerator will verify that the OU layout
# matches before continuing to execute the deployment pipeline.

enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: Education
quarantineNewAccounts:
  enable: true
  scpPolicyName: Quarantine
serviceControlPolicies:
  - name: AcceleratorGuardrails1
    description: >
      Accelerator GuardRails 1
    policy: service-control-policies/guardrails-1.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Infrastructure
  - name: AcceleratorGuardrails2
    description: >
      Accelerator GuardRails 2
    policy: service-control-policies/guardrails-2.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Infrastructure
  - name: Quarantine
    description: >
      This SCP is used to prevent changes to new accounts until the Accelerator
      has been executed successfully.
      This policy will be applied upon account creation if enabled.
    policy: service-control-policies/quarantine.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: []
  # Education Focused SCPs
  - name: EducationSCP
    description: >
      Education Controls SCP for Education OU
    policy: service-control-policies/scp-education.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Education
  # Not deployed by default, edit SCP for appropriate regions and deploy if needed.
  - name: EducationSCP2
    description: >
      Education Controls to allow only specific s3 bucket regions
    policy: service-control-policies/scp-education-2.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: []
 # https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_tag-policies.html
taggingPolicies:
  - name: TagPolicy
    description: Organization Tagging Policy
    policy: tagging-policies/org-tag-policy.json
    deploymentTargets:
      organizationalUnits:
        - Root
# https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_backup.html
# backup policies contain a `delete_after_days` value of 1095 days, or 3 years.  Before
# enabling this policy, ensure that `delete_after_days` meets your organization's records retention
# policies.  Similarly, ensure that `move_to_cold_storage_after_days` meets business requirements.
backupPolicies:
  - name: BackupPolicy
    description: Organization Backup Policy
    policy: backup-policies/backup-plan.json
    deploymentTargets:
      organizationalUnits:
        - Root
